/**
 * preload — Act-aware audio asset preloading (spec 11 §5).
 *
 * Maps each Act number to the set of SFX + music + ambience assets it
 * needs, then preloads them via SfxPool / MusicPlayer / AmbienceLayer.
 *
 * Spec 11 §5.2: 3 instances per SFX are preloaded per Act so rapid-fire
 * triggers (sword swings, footstep chains) don't queue on one instance.
 *
 * For now the manifest is a simple object literal in this file (per task
 * P1.E4.T5). A future task will swap it for a JSON manifest generated by
 * the bake script (spec 11 §9.1).
 */

import { logger } from '@/shared/log';

import { musicPlayer } from './MusicPlayer';
import { sfxPool } from './SfxPool';

/** Number of SFX instances to preload per sound id (spec 11 §5.2). */
export const SFX_INSTANCES_PER_SOUND = 3;

/** File path prefixes (relative to basePath = Sound.MAIN_BUNDLE). */
const SFX_PREFIX = 'sfx/';
const MUSIC_PREFIX = 'music/';
const AMBIENCE_PREFIX = 'ambience/';

/** Per-Act audio manifest. */
export interface ActAudioManifest {
  /** Music track ids (without extension) for this Act. */
  music?: string[];
  /** Ambience bed ids (without extension) for this Act. */
  ambience?: string[];
  /** SFX id → relative file path under `sfx/` for this Act. */
  sfx?: Record<string, string>;
}

/**
 * Act → manifest table. Each Act lists the music/ambience/sfx it needs.
 *
 * Act 0 is the Prologue (tutorial). Acts 1-11 follow spec 11 §2.1.
 * Acts not yet authored fall back to Act 0's manifest.
 */
export const ACT_AUDIO_MANIFEST: Record<number, ActAudioManifest> = {
  0: {
    music: ['tutorial'],
    ambience: ['amb_act1'],
    sfx: {
      footstep_grass: 'world/footstep_grass.ogg',
      menu_select: 'ui/menu_select.ogg',
      menu_back: 'ui/menu_back.ogg',
    },
  },
  1: {
    music: ['act1_explore', 'boss_phase1', 'boss_phase2', 'victory', 'defeat'],
    ambience: ['amb_act1'],
    sfx: {
      sword_swing: 'combat/sword_swing.ogg',
      sword_hit: 'combat/sword_hit.ogg',
      dodge: 'combat/dodge.ogg',
      defend: 'combat/defend.ogg',
      death_enemy: 'combat/death_enemy.ogg',
      pickup: 'items/pickup.ogg',
      chest_open: 'items/chest_open.ogg',
      door_open: 'world/door_open.ogg',
      footstep_grass: 'world/footstep_grass.ogg',
      puzzle_solve: 'puzzle/puzzle_solve.ogg',
      puzzle_fail: 'puzzle/puzzle_fail.ogg',
      menu_select: 'ui/menu_select.ogg',
      menu_back: 'ui/menu_back.ogg',
    },
  },
  2: {
    music: ['act2_explore', 'boss_phase1', 'boss_phase2', 'victory', 'defeat'],
    ambience: ['amb_act2'],
    sfx: {
      sword_swing: 'combat/sword_swing.ogg',
      sword_hit: 'combat/sword_hit.ogg',
      dodge: 'combat/dodge.ogg',
      magic_cast: 'combat/magic_cast.ogg',
      death_enemy: 'combat/death_enemy.ogg',
      footstep_water: 'world/footstep_water.ogg',
      pickup: 'items/pickup.ogg',
      chest_open: 'items/chest_open.ogg',
      puzzle_solve: 'puzzle/puzzle_solve.ogg',
      puzzle_fail: 'puzzle/puzzle_fail.ogg',
    },
  },
  3: {
    music: ['act3_explore', 'boss_phase1', 'boss_phase2', 'victory', 'defeat'],
    ambience: ['amb_act3'],
    sfx: {
      sword_swing: 'combat/sword_swing.ogg',
      sword_hit: 'combat/sword_hit.ogg',
      magic_cast: 'combat/magic_cast.ogg',
      ranged: 'combat/ranged.ogg',
      death_enemy: 'combat/death_enemy.ogg',
      footstep_grass: 'world/footstep_grass.ogg',
      pickup: 'items/pickup.ogg',
      puzzle_solve: 'puzzle/puzzle_solve.ogg',
      puzzle_fail: 'puzzle/puzzle_fail.ogg',
    },
  },
  4: {
    music: ['act4_explore', 'boss_phase1', 'boss_phase2', 'victory', 'defeat'],
    ambience: ['amb_act4'],
    sfx: {
      sword_swing: 'combat/sword_swing.ogg',
      sword_hit: 'combat/sword_hit.ogg',
      defend: 'combat/defend.ogg',
      death_enemy: 'combat/death_enemy.ogg',
      footstep_stone: 'world/footstep_stone.ogg',
      pickup: 'items/pickup.ogg',
      puzzle_solve: 'puzzle/puzzle_solve.ogg',
      puzzle_fail: 'puzzle/puzzle_fail.ogg',
    },
  },
  5: {
    music: ['act5_explore', 'boss_phase1', 'boss_phase2', 'victory', 'defeat'],
    ambience: ['amb_act5'],
    sfx: {
      sword_swing: 'combat/sword_swing.ogg',
      sword_hit: 'combat/sword_hit.ogg',
      crate_push: 'puzzle/crate_push.ogg',
      switch_toggle: 'puzzle/switch_toggle.ogg',
      death_enemy: 'combat/death_enemy.ogg',
      footstep_water: 'world/footstep_water.ogg',
      pickup: 'items/pickup.ogg',
      puzzle_solve: 'puzzle/puzzle_solve.ogg',
      puzzle_fail: 'puzzle/puzzle_fail.ogg',
    },
  },
  6: {
    music: ['act6_explore', 'boss_phase1', 'boss_phase2', 'victory', 'defeat'],
    ambience: ['amb_act6'],
    sfx: {
      sword_swing: 'combat/sword_swing.ogg',
      sword_hit: 'combat/sword_hit.ogg',
      magic_cast: 'combat/magic_cast.ogg',
      death_enemy: 'combat/death_enemy.ogg',
      footstep_water: 'world/footstep_water.ogg',
      pickup: 'items/pickup.ogg',
      puzzle_solve: 'puzzle/puzzle_solve.ogg',
      puzzle_fail: 'puzzle/puzzle_fail.ogg',
    },
  },
  7: {
    music: ['act7_explore', 'boss_phase1', 'boss_phase2', 'victory', 'defeat'],
    ambience: ['amb_act7'],
    sfx: {
      sword_swing: 'combat/sword_swing.ogg',
      sword_hit: 'combat/sword_hit.ogg',
      block: 'combat/block.ogg',
      parry: 'combat/parry.ogg',
      death_enemy: 'combat/death_enemy.ogg',
      footstep_stone: 'world/footstep_stone.ogg',
      pickup: 'items/pickup.ogg',
      puzzle_solve: 'puzzle/puzzle_solve.ogg',
      puzzle_fail: 'puzzle/puzzle_fail.ogg',
    },
  },
  8: {
    music: ['act8_explore', 'boss_phase1', 'boss_phase2', 'victory', 'defeat'],
    ambience: ['amb_act8'],
    sfx: {
      sword_swing: 'combat/sword_swing.ogg',
      sword_hit: 'combat/sword_hit.ogg',
      fire_hit: 'combat/fire_hit.ogg',
      death_enemy: 'combat/death_enemy.ogg',
      footstep_stone: 'world/footstep_stone.ogg',
      pickup: 'items/pickup.ogg',
      puzzle_solve: 'puzzle/puzzle_solve.ogg',
      puzzle_fail: 'puzzle/puzzle_fail.ogg',
    },
  },
  9: {
    music: ['act9_explore', 'boss_phase1', 'boss_phase2', 'victory', 'defeat'],
    ambience: ['amb_act9'],
    sfx: {
      sword_swing: 'combat/sword_swing.ogg',
      sword_hit: 'combat/sword_hit.ogg',
      ranged: 'combat/ranged.ogg',
      death_enemy: 'combat/death_enemy.ogg',
      footstep_stone: 'world/footstep_stone.ogg',
      pickup: 'items/pickup.ogg',
      puzzle_solve: 'puzzle/puzzle_solve.ogg',
      puzzle_fail: 'puzzle/puzzle_fail.ogg',
    },
  },
  10: {
    music: ['act10_explore', 'boss_phase1', 'boss_phase2', 'victory', 'defeat'],
    ambience: ['amb_act10'],
    sfx: {
      sword_swing: 'combat/sword_swing.ogg',
      sword_hit: 'combat/sword_hit.ogg',
      ranged: 'combat/ranged.ogg',
      death_enemy: 'combat/death_enemy.ogg',
      footstep_water: 'world/footstep_water.ogg',
      pickup: 'items/pickup.ogg',
      puzzle_solve: 'puzzle/puzzle_solve.ogg',
      puzzle_fail: 'puzzle/puzzle_fail.ogg',
    },
  },
  11: {
    music: ['act11_explore', 'boss_phase1', 'boss_phase2', 'victory', 'defeat'],
    ambience: ['amb_act11'],
    sfx: {
      sword_swing: 'combat/sword_swing.ogg',
      sword_hit: 'combat/sword_hit.ogg',
      heal: 'combat/heal.ogg',
      level_up: 'combat/level_up.ogg',
      death_enemy: 'combat/death_enemy.ogg',
      footstep_stone: 'world/footstep_stone.ogg',
      pickup: 'items/pickup.ogg',
      puzzle_solve: 'puzzle/puzzle_solve.ogg',
      puzzle_fail: 'puzzle/puzzle_fail.ogg',
    },
  },
  12: {
    music: ['act12_explore', 'boss_phase1', 'boss_phase2', 'victory', 'defeat', 'game_over'],
    ambience: ['amb_act12'],
    sfx: {
      sword_swing: 'combat/sword_swing.ogg',
      sword_hit: 'combat/sword_hit.ogg',
      death_player: 'combat/death_player.ogg',
      death_enemy: 'combat/death_enemy.ogg',
      footstep_stone: 'world/footstep_stone.ogg',
      pickup: 'items/pickup.ogg',
      relic_collect: 'story/relic_collect.ogg',
      achievement: 'story/achievement.ogg',
      puzzle_solve: 'puzzle/puzzle_solve.ogg',
      puzzle_fail: 'puzzle/puzzle_fail.ogg',
    },
  },
};

/** Build the absolute file path for a music track id. */
export function musicFilePath(trackId: string): string {
  return `${MUSIC_PREFIX}${trackId}.ogg`;
}

/** Build the absolute file path for an ambience bed id. */
export function ambienceFilePath(bedId: string): string {
  return `${AMBIENCE_PREFIX}${bedId}.ogg`;
}

/** Build the absolute file path for an SFX (sfx-relative path already includes subfolder). */
export function sfxFilePath(relativePath: string): string {
  return `${SFX_PREFIX}${relativePath}`;
}

/** Resolve an act number to its manifest (falls back to Act 0 if unknown). */
export function getActManifest(actNumber: number): ActAudioManifest {
  return ACT_AUDIO_MANIFEST[actNumber] ?? ACT_AUDIO_MANIFEST[0];
}

/**
 * Preload all SFX and music assets required for the given Act.
 *
 *  - SFX: preloaded into the pool, 3 instances each (spec 11 §5.2).
 *  - Music: TrackPlayer streams on demand; we call MusicPlayer.preload()
 *    for API symmetry but it is currently a no-op.
 *  - Ambience: preloaded into the AmbienceLayer; beds start looping only
 *    when `ambienceLayer.play(bedId, file)` is explicitly called from
 *    the scene manager. Here we only warm the Sound instances by
 *    preloading them once (then immediately stopping — they'll be
 *    re-created on play()).
 *
 * Errors for individual assets are logged and swallowed — partial
 * preloading is preferable to aborting the whole Act load.
 */
export async function preloadAudioForAct(actNumber: number): Promise<void> {
  const manifest = getActManifest(actNumber);
  logger.info(`[audio] preloading assets for Act ${actNumber}`);

  // SFX: 3 instances each. Preloads run in parallel — `new Sound(...)`
  // completes asynchronously on device, so awaiting each instance serially
  // would make an Act's preload take ~3× longer than necessary (the load
  // callback, not JS, is the bottleneck; the pool is safe for concurrent
  // preloads).
  if (manifest.sfx) {
    const tasks: Array<Promise<void>> = [];
    for (const [id, relPath] of Object.entries(manifest.sfx)) {
      const file = sfxFilePath(relPath);
      for (let i = 0; i < SFX_INSTANCES_PER_SOUND; i++) {
        tasks.push(
          sfxPool.preload(id, file).catch((e: unknown) => {
            logger.warn(`[audio] sfx preload failed for "${id}"`, e);
          }),
        );
      }
    }
    await Promise.all(tasks);
  }

  // Music: TrackPlayer streams on demand; preload() is a no-op today.
  if (manifest.music && manifest.music.length > 0) {
    const tracks = manifest.music.map((id) => ({
      id,
      url: musicFilePath(id),
      title: id,
    }));
    try {
      await musicPlayer.preload(tracks);
    } catch (e) {
      logger.warn('[audio] music preload failed', e);
    }
  }

  // Ambience: the manifest records which beds this Act needs, but
  // AmbienceLayer doesn't expose a preload() — beds are loaded
  // on-demand when the scene manager calls ambienceLayer.play().
  // We record the manifest here so a future optimisation can warm
  // the Sound instances without changing call sites.
  if (manifest.ambience && manifest.ambience.length > 0) {
    logger.debug(
      `[audio] ambience manifest for Act ${actNumber}: ${manifest.ambience.join(', ')}`,
    );
  }
}
